import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "prod-iphone-16-pro",
    slug: "iphone-16-pro",
    name: "Apple iPhone 16 Pro",
    brand: "Apple",
    tagline: "Titanium design. A18 Pro chip. Camera Control.",
    description:
      "iPhone 16 Pro features a Grade 5 titanium design with a new refined microblasted finish. Powered by the industry-leading A18 Pro chip with 6-core GPU, next-generation photographic styles, and 4K 120 fps Dolby Vision recording.",
    badge: "0% EMI",
    isNew: true,
    isPopular: true,
    thumbnail: "/products/iphone-16-pro.webp",
    images: [
      "/products/iphone-16-pro.webp",
      "/products/iphone-16.webp",
    ],
    partnerLender: "Tata Capital Financial Services",
    keyFeatures: [
      "Grade 5 Titanium with textured matte-glass back",
      "A18 Pro chip with 6-core GPU and Neural Engine",
      "48MP Fusion camera with 5x Telephoto zoom",
      "Up to 27 hours video playback",
    ],
    specs: {
      display: '6.3" Super Retina XDR OLED, 120Hz ProMotion',
      processor: "Apple A18 Pro (3nm)",
      camera: "48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto",
      battery: "3,582 mAh with 25W MagSafe charging",
      os: "iOS 18 with Apple Intelligence",
      warranty: "1 Year Apple India Warranty",
    },
    variants: [
      {
        id: "var-ip16p-128-natural",
        storage: "128 GB",
        color: "Natural Titanium",
        colorHex: "#9B968E",
        mrp: 119900,
        sellingPrice: 114900,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-ip16p-256-natural",
        storage: "256 GB",
        color: "Natural Titanium",
        colorHex: "#9B968E",
        mrp: 129900,
        sellingPrice: 124900,
        cashback: 2500,
        inStock: true,
      },
      {
        id: "var-ip16p-512-natural",
        storage: "512 GB",
        color: "Natural Titanium",
        colorHex: "#9B968E",
        mrp: 149900,
        sellingPrice: 144900,
        cashback: 3000,
        inStock: true,
      },
      {
        id: "var-ip16p-128-desert",
        storage: "128 GB",
        color: "Desert Titanium",
        colorHex: "#C4A587",
        mrp: 119900,
        sellingPrice: 114900,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-ip16p-256-desert",
        storage: "256 GB",
        color: "Desert Titanium",
        colorHex: "#C4A587",
        mrp: 129900,
        sellingPrice: 124900,
        cashback: 2500,
        inStock: true,
      },
      {
        id: "var-ip16p-128-black",
        storage: "128 GB",
        color: "Black Titanium",
        colorHex: "#353638",
        mrp: 119900,
        sellingPrice: 114900,
        cashback: 2000,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-iphone-16",
    slug: "iphone-16",
    name: "Apple iPhone 16",
    brand: "Apple",
    tagline: "Camera Control. 48MP Fusion. Vivid saturated colors.",
    description:
      "Meet iPhone 16 with Camera Control, 48MP Fusion camera with 2x optical-quality Telephoto, the ultrafast A18 chip, and an aerospace-grade aluminum enclosure.",
    badge: "Bestseller",
    isNew: true,
    isPopular: true,
    thumbnail: "/products/iphone-16.webp",
    images: [
      "/products/iphone-16.webp",
      "/products/iphone-16-pro.webp",
    ],
    partnerLender: "Bajaj Finserv Limited",
    keyFeatures: [
      "Aerospace-grade aluminum with color-infused glass back",
      "Action button and new Camera Control tactile sensor",
      "A18 chip built for Apple Intelligence",
      "All-day battery life up to 22 hours",
    ],
    specs: {
      display: '6.1" Super Retina XDR OLED',
      processor: "Apple A18 (3nm)",
      camera: "48MP Fusion + 12MP Ultra Wide with Macro",
      battery: "3,561 mAh",
      os: "iOS 18",
      warranty: "1 Year Apple India Warranty",
    },
    variants: [
      {
        id: "var-ip16-128-ultra",
        storage: "128 GB",
        color: "Ultramarine",
        colorHex: "#3559B0",
        mrp: 79900,
        sellingPrice: 74900,
        cashback: 1500,
        inStock: true,
      },
      {
        id: "var-ip16-256-ultra",
        storage: "256 GB",
        color: "Ultramarine",
        colorHex: "#3559B0",
        mrp: 89900,
        sellingPrice: 84900,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-ip16-128-teal",
        storage: "128 GB",
        color: "Teal",
        colorHex: "#8CB3AC",
        mrp: 79900,
        sellingPrice: 74900,
        cashback: 1500,
        inStock: true,
      },
      {
        id: "var-ip16-128-pink",
        storage: "128 GB",
        color: "Pink",
        colorHex: "#E5A9BD",
        mrp: 79900,
        sellingPrice: 74900,
        cashback: 1500,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-samsung-galaxy-s24-ultra",
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    tagline: "Galaxy AI is here. Titanium shield. 200MP detail.",
    description:
      "Welcome to the era of mobile AI. With Galaxy S24 Ultra, you can unleash whole new levels of creativity, productivity, and possibility, starting with the most important device in your life.",
    badge: "0% EMI",
    isNew: false,
    isPopular: true,
    thumbnail: "/products/galaxy-s24-ultra.webp",
    images: [
      "/products/galaxy-s24-ultra.webp",
      "/products/galaxy-s24.webp",
    ],
    partnerLender: "Tata Capital Financial Services",
    keyFeatures: [
      "Titanium frame with Corning Gorilla Armor anti-reflective glass",
      "Built-in S Pen with air gestures",
      "Galaxy AI: Circle to Search, Live Translate, Note Assist",
      "Quad Tele System with 50MP 5x optical zoom and 100x Space Zoom",
    ],
    specs: {
      display: '6.8" Dynamic AMOLED 2X, QHD+, 1-120Hz, 2600 nits',
      processor: "Snapdragon 8 Gen 3 for Galaxy",
      camera: "200MP Wide + 50MP 5x Tele + 12MP Ultra Wide + 10MP 3x Tele",
      battery: "5,000 mAh with 45W fast charging",
      os: "Android 14 with One UI 6.1 (7 years updates)",
      warranty: "1 Year Comprehensive Manufacturer Warranty",
    },
    variants: [
      {
        id: "var-s24u-256-gray",
        storage: "256 GB",
        color: "Titanium Gray",
        colorHex: "#7B7977",
        mrp: 134999,
        sellingPrice: 121999,
        cashback: 3000,
        inStock: true,
      },
      {
        id: "var-s24u-512-gray",
        storage: "512 GB",
        color: "Titanium Gray",
        colorHex: "#7B7977",
        mrp: 144999,
        sellingPrice: 131999,
        cashback: 3500,
        inStock: true,
      },
      {
        id: "var-s24u-256-black",
        storage: "256 GB",
        color: "Titanium Black",
        colorHex: "#2C2D30",
        mrp: 134999,
        sellingPrice: 121999,
        cashback: 3000,
        inStock: true,
      },
      {
        id: "var-s24u-256-violet",
        storage: "256 GB",
        color: "Titanium Violet",
        colorHex: "#4C465A",
        mrp: 134999,
        sellingPrice: 121999,
        cashback: 3000,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-samsung-galaxy-s24",
    slug: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24 5G",
    brand: "Samsung",
    tagline: "Compact powerhouse with all Galaxy AI features.",
    description:
      "A simplified, satin-finish design with enhanced Armor Aluminum frame. Compact 6.2-inch form factor with full Galaxy AI intelligence.",
    badge: "Trending",
    isNew: false,
    isPopular: false,
    thumbnail: "/products/galaxy-s24.webp",
    images: [
      "/products/galaxy-s24.webp",
      "/products/galaxy-s24-ultra.webp",
    ],
    partnerLender: "DSP Finance Private Limited",
    keyFeatures: [
      "Enhanced Armor Aluminum frame with IP68 water resistance",
      "Circle to Search with Google and AI photo editing",
      "Vapor chamber cooling 1.5x larger for sustained performance",
      "7 generations of OS upgrades and security updates",
    ],
    specs: {
      display: '6.2" Dynamic AMOLED 2X, FHD+, 1-120Hz',
      processor: "Samsung Exynos 2400 Deca-Core (4nm)",
      camera: "50MP Main with OIS + 12MP Ultra Wide + 10MP 3x Telephoto",
      battery: "4,000 mAh with 25W charging",
      os: "Android 14 with One UI 6.1",
      warranty: "1 Year Samsung India Warranty",
    },
    variants: [
      {
        id: "var-s24-128-onyx",
        storage: "128 GB",
        color: "Onyx Black",
        colorHex: "#222325",
        mrp: 74999,
        sellingPrice: 62999,
        cashback: 1500,
        inStock: true,
      },
      {
        id: "var-s24-256-onyx",
        storage: "256 GB",
        color: "Onyx Black",
        colorHex: "#222325",
        mrp: 79999,
        sellingPrice: 67999,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-s24-128-marble",
        storage: "128 GB",
        color: "Marble Gray",
        colorHex: "#D8D9DC",
        mrp: 74999,
        sellingPrice: 62999,
        cashback: 1500,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-google-pixel-9-pro",
    slug: "google-pixel-9-pro",
    name: "Google Pixel 9 Pro",
    brand: "Google",
    tagline: "Engineered by Google. Built for Gemini AI.",
    description:
      "Pixel 9 Pro features a sleek, sophisticated design with a polished metal frame and matte glass back. Powered by the next-generation Tensor G4 chip, it brings Google's most powerful Gemini AI models right into your pocket.",
    badge: "0% EMI",
    isNew: true,
    isPopular: true,
    thumbnail: "/products/pixel-9-pro.webp",
    images: [
      "/products/pixel-9-pro.webp",
      "/products/pixel-9.webp",
    ],
    partnerLender: "Tata Capital Financial Services",
    keyFeatures: [
      "Google Tensor G4 processor with Titan M2 security coprocessor",
      "Super Actua display with 3,000 nits peak brightness",
      "Pro triple camera system with 8K video boost",
      "Gemini Live conversational assistance built-in",
    ],
    specs: {
      display: '6.3" Super Actua LTPO OLED, 1-120Hz, 3000 nits',
      processor: "Google Tensor G4 (4nm)",
      camera: "50MP Main + 48MP Ultra Wide + 48MP 5x Telephoto",
      battery: "4,700 mAh with 27W fast charging",
      os: "Android 14 (7 years of Pixel Drops & OS upgrades)",
      warranty: "1 Year Google India Warranty",
    },
    variants: [
      {
        id: "var-px9p-128-porcelain",
        storage: "128 GB",
        color: "Porcelain",
        colorHex: "#F2EFE9",
        mrp: 109999,
        sellingPrice: 102999,
        cashback: 2500,
        inStock: true,
      },
      {
        id: "var-px9p-256-porcelain",
        storage: "256 GB",
        color: "Porcelain",
        colorHex: "#F2EFE9",
        mrp: 119999,
        sellingPrice: 112999,
        cashback: 3000,
        inStock: true,
      },
      {
        id: "var-px9p-128-obsidian",
        storage: "128 GB",
        color: "Obsidian",
        colorHex: "#2E2F32",
        mrp: 109999,
        sellingPrice: 102999,
        cashback: 2500,
        inStock: true,
      },
      {
        id: "var-px9p-128-hazel",
        storage: "128 GB",
        color: "Hazel",
        colorHex: "#6F7570",
        mrp: 109999,
        sellingPrice: 102999,
        cashback: 2500,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-google-pixel-9",
    slug: "google-pixel-9",
    name: "Google Pixel 9",
    brand: "Google",
    tagline: "Gemini intelligence. Iconic camera. Fresh colors.",
    description:
      "Pixel 9 is powered by the Google Tensor G4 chip, giving you the best of Google AI first. Capture stunning photos with the advanced dual rear camera system and keep your data private.",
    badge: "New Launch",
    isNew: true,
    isPopular: false,
    thumbnail: "/products/pixel-9.webp",
    images: [
      "/products/pixel-9.webp",
      "/products/pixel-9-pro.webp",
    ],
    partnerLender: "Bajaj Finserv Limited",
    keyFeatures: [
      "Google Tensor G4 chip with 12GB RAM for smooth multitasking",
      "Actua display 35% brighter than Pixel 8",
      "Add Me camera feature so nobody is left out of group photos",
      "IP68 water and dust resistance",
    ],
    specs: {
      display: '6.3" Actua OLED, 60-120Hz, 2700 nits',
      processor: "Google Tensor G4",
      camera: "50MP Wide + 48MP Ultra Wide with Macro Focus",
      battery: "4,700 mAh with 27W charging",
      os: "Android 14 with 7 years of updates",
      warranty: "1 Year Google India Warranty",
    },
    variants: [
      {
        id: "var-px9-128-peony",
        storage: "128 GB",
        color: "Peony",
        colorHex: "#F78D9F",
        mrp: 79999,
        sellingPrice: 74999,
        cashback: 1500,
        inStock: true,
      },
      {
        id: "var-px9-256-peony",
        storage: "256 GB",
        color: "Peony",
        colorHex: "#F78D9F",
        mrp: 89999,
        sellingPrice: 84999,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-px9-128-wintergreen",
        storage: "128 GB",
        color: "Wintergreen",
        colorHex: "#A0D5BD",
        mrp: 79999,
        sellingPrice: 74999,
        cashback: 1500,
        inStock: true,
      },
    ],
  },
  {
    id: "prod-oneplus-12",
    slug: "oneplus-12",
    name: "OnePlus 12 5G",
    brand: "OnePlus",
    tagline: "Smooth Beyond Belief. 4th Gen Hasselblad Camera.",
    description:
      "Powered by Snapdragon 8 Gen 3 with up to 16GB of LPDDR5X RAM and ultra-fast 100W SUPERVOOC charging. Featuring a 2K 120 Hz ProXDR display and 4th Gen Hasselblad Camera for Mobile.",
    badge: "0% EMI",
    isNew: false,
    isPopular: true,
    thumbnail: "/products/oneplus-12.webp",
    images: [
      "/products/oneplus-12.webp",
      "/products/galaxy-s24-ultra.webp",
    ],
    partnerLender: "Tata Capital Financial Services",
    keyFeatures: [
      "Snapdragon 8 Gen 3 with Dual Cryo-velocity VC cooling",
      "100W SUPERVOOC wired + 50W AIRVOOC wireless fast charging",
      "4th Gen Hasselblad Camera with Sony's LYT-808 sensor",
      "5,400 mAh high-capacity battery",
    ],
    specs: {
      display: '6.82" 2K 120Hz ProXDR AMOLED with Aqua Touch, 4500 nits',
      processor: "Qualcomm Snapdragon 8 Gen 3",
      camera: "50MP Main + 64MP 3x Periscope Tele + 48MP Ultra Wide",
      battery: "5,400 mAh with 100W SUPERVOOC included in box",
      os: "OxygenOS 14 based on Android 14",
      warranty: "1 Year OnePlus Official Warranty",
    },
    variants: [
      {
        id: "var-op12-256-emerald",
        storage: "256 GB",
        color: "Flowy Emerald",
        colorHex: "#2C5248",
        mrp: 64999,
        sellingPrice: 59999,
        cashback: 1500,
        inStock: true,
      },
      {
        id: "var-op12-512-emerald",
        storage: "512 GB",
        color: "Flowy Emerald",
        colorHex: "#2C5248",
        mrp: 69999,
        sellingPrice: 64999,
        cashback: 2000,
        inStock: true,
      },
      {
        id: "var-op12-256-black",
        storage: "256 GB",
        color: "Silky Black",
        colorHex: "#1F1F21",
        mrp: 64999,
        sellingPrice: 59999,
        cashback: 1500,
        inStock: true,
      },
    ],
  },
];
